### ISSUE TITLE
Cannot follow README.md instructions: HelloWorld example missing

### ISSUE THREAD

**Issue by ceresek** [jagotu/BACIL#2]
The instructions mention `HelloWorld.dll`, but it is not included in the build ?

**Comment by jagotu** [comment]
The example expected the user to already have assemblies they want to run.

To make running BACIL easier, I created a [BACIL_examples repository](https://github.com/jagotu/BACIL_examples) that contains a prebuilt example assembly and updated README.md to reference it.
